const data = [
  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fc7b3c28-d2d4-46b4-921f-38c7abde435a/romaleos-4-se-weightlifting-shoe-Sn85Sc.png',
    title: 'Nike Romaleos 4',
    desc: 'The best Weightlifting Shoe',
    star: 4.2,
    reviews: '(123 reviews)',
    prevPrice: '$ 140',
    newPrice: '200',
    company: 'Nike',
    color: 'white',
    category: 'shoes',
  },
  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8d3ec4e3-a62a-46ba-a8cd-dc34f3270101/metcon-9-amp-training-shoes-2RbT53.png',
    title: 'NikeMetcon 9',
    desc: 'The best Training Shoe',
    star: 4,
    reviews: '(123 reviews)',

    newPrice: '100',
    company: 'Nike',
    color: 'white',
    category: 'shoes',
  },

  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c62b916a-063a-460e-b5dc-0727bf0a22d0/pegasus-turbo-road-running-shoes-GH2jt1.png',
    title: 'Nike Pegasus Turbo',
    desc: 'The best Running Shoe',
    star: 5,
    reviews: '(123 reviews)',
    prevPrice: '$ 240',
    newPrice: '180',
    company: 'Nike',
    color: 'green',
    category: 'shoes',
  },
  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bf21c995-9a84-42f2-9f0c-ab66bd980712/dri-fit-multi-older-printed-training-shorts-K2D3gZ.png',
    title: 'Nike Dri-FIT Mulity+',
    desc: 'The best Training Shorts',
    star: 5,
    reviews: '(123 reviews)',

    newPrice: '50',
    company: 'Nike',
    color: 'gray',
    category: 'clothes',
  },
  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/4ff563e2-732c-4183-86f4-5318fd1e0881/hike-backpack-7RvBfK.png',
    title: 'Nike Hike',
    desc: 'The best Grips',
    star: 5,
    reviews: '(123 reviews)',

    newPrice: '100',
    company: 'Nike',
    color: 'black',
    category: 'equipment',
  },
  {
    img: 'https://m.media-amazon.com/images/I/71CQ6esBqFL._AC_SL1500_.jpg',
    title: 'Whoop 4.0',
    desc: 'The best Fitness Tracker',
    star: 4.7,
    reviews: '(13 reviews)',
    prevPrice: '$ 330',
    newPrice: '200',
    company: 'Whoop',
    color: 'black',
    category: 'equipment',
  },

  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e45e0e59-ed74-4e47-b175-b1fbe349ae3a/brasilia-9-5-training-duffel-bag-lrNngk.png',
    title: 'Nike Brasilia 9.5',
    desc: 'Good for your stuff',
    star: 4,
    reviews: '(13 reviews)',

    newPrice: '50',
    company: 'Nike',
    color: 'blue',
    category: 'equipment',
  },

  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1f3a5cb0-5ad5-4e72-acf1-4d44fcd99a6f/printed-stash-shoe-bag-Z2s8Pv.png',
    title: 'Nike Printed Stash Shoe Bag',
    desc: 'A bag for your shoes',
    star: 4,
    reviews: '(123 reviews)',

    newPrice: '100',
    company: 'Nike',
    color: 'black',
    category: 'equipment',
  },

  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8308f7c4-b836-4c15-8484-67602ae39dd2/tempo-road-running-shoes-zwkW5t.png',
    title: 'Nike Air Zoom Tempo Next',
    desc: 'The best Running Shoe',
    star: 5,
    reviews: '(190 reviews)',
    prevPrice: '$ 240',
    newPrice: '200',
    company: 'Nike',
    color: 'white',
    category: 'shoes',
  },

  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1af9c87c-6e11-4bc6-ad66-648558bc49b7/vaporfly-3-road-racing-shoes-XZZSbK.png',
    title: 'Nike Vaporfly 3',
    desc: 'The best Running Shoe',
    star: 5,
    reviews: '(1323 reviews)',
    prevPrice: '$ 290',
    newPrice: '200',
    company: 'Nike',
    color: 'White',
    category: 'shoes',
  },
  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/441fd070-b21d-4ccc-a9cd-380455b44151/free-metcon-5-workout-shoes-0nJCzq.png',
    title: 'Nike Free Metcon 5',
    desc: 'The best Training Shoe',
    star: 5,
    reviews: '(1323 reviews)',
    prevPrice: '$ 290',
    newPrice: '150',
    company: 'Nike',
    color: 'gray',
    category: 'shoes',
  },
  {
    img: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c1dcc424-1008-4510-97f3-59d6cf3be65f/utility-power-training-duffel-bag-MdD62t.png',
    title: 'Nike Utility Power',
    desc: 'The best Training Bag',
    star: 5,
    reviews: '(1323 reviews)',
    prevPrice: '$ 70',
    newPrice: '50',
    company: 'Nike',
    color: 'blue',
    category: 'equipment ',
  },
];

export default data;
